from typing import Dict, Any, Optional

class HardwareIdentifier:
    cache: dict
    
    def __init__(self) -> None: ...
    
    def get_hardware_id(self) -> str: ...
    
    def verify_hardware_id(self, stored_id: str) -> bool: ...
    
    def get_hardware_fingerprint(self) -> Dict[str, Any]: ...